# @package _global_

# specify here default training configuration
defaults:
  - trainer: default
  - lightning_module/loss: mse
  - lightning_module: localization
  - model: resnet50
  - transforms@train_transforms: strong
  - transforms@image_transforms: resize_normalize
  - datamodule: indian_diabetic_retinopathy_localization
  - callbacks: none
  - logger: mlflow

  - hydra: default
  - environment: local
  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

  - _self_

logger:
  experiment_name: localization

model:
  num_output_units: 4

# seed for the random number generators
seed: 42

# print config at the start of the run
print_config: True

# Path to model checkpoint.
load_model: null

# Filename to save final model to
save_model: null

# patch size
image_size: 256
