# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - trainer: default
  - lightning_module: simclr
  - model: resnet_backbone
  - transforms@ssl_transforms: simclr_aug
  - transforms@test_transforms: resize_normalize
  - datamodule: ssl_diabetic_retinopathy
  - callbacks: none
  - logger: mlflow
  - experiment: simclr_drd

  - hydra: mlflow
  - environment: local
  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

# seed for the random number generators
seed: 42

# print config at the start of the run
print_config: True

# Path to model checkpoint.
load_model: null

# Filename to save final model to
save_model: null

# patch size
image_size: 256
