# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - trainer: default
  - lightning_module: simclr
  - model: resnet
  - transforms: weak
  - datamodule: ssl_diabetic_retinopathy
  - callbacks: none
  - logger: mlflow

  - hydra: default
  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

  - environment: local

# seed for the random number generators
seed: 42

# print config at the start of the run
print_config: True

# Path to model checkpoint.
load_model: null

# Filename to save final model to
save_model: null
