_target_: ophthalmology.data.modules.DiabeticRetinopythyDetection

image_dir: ${environment.datadir}/diabetic-retinopathy-detection/images
csv_file_train: ${environment.datadir}/diabetic-retinopathy-detection/train_labels_cleaned.csv
csv_file_test: ${environment.datadir}/diabetic-retinopathy-detection/test_labels_cleaned.csv

train_test_split: 0.9
batch_size: 64
pin_memory: True
num_workers: 1
seed: ${seed}
