_target_: ophthalmology.data.modules.SSLDiabeticRetinopythyDetection

image_dir: ${environment.data_dir}/diabetic-retinopathy-detection/images
csv_file: ${environment.data_dir}/diabetic-retinopathy-detection/all_labels.csv

train_test_split: 0.98
batch_size: 64
num_workers: 1
seed: 42
