_recursive_: True
_convert_: partial
_target_: torchvision.transforms.Compose
_args_:
  -
    - _target_: torchvision.transforms.RandomHorizontalFlip
    - _target_: torchvision.transforms.RandomVerticalFlip
    - _target_: ophthalmology.layers.noise.RandomGaussianNoise
      var: 0.1
      apply_prob: 0.3
    - _target_: torchvision.transforms.RandomRotation
      _args_:
        - 180
    - _target_: torchvision.transforms.GaussianBlur
      _args_:
        - 3
        - [0.001, 0.6]
