_recursive_: True
_convert_: partial
_target_: torchvision.transforms.Compose
_args_:
  -
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Resize
      _args_:
        -
          - ${image_size}
          - ${image_size}
    - _target_: torchvision.transforms.Normalize
      _args_:
        -
          - 0.3211
          - 0.2243
          - 0.1602
        -
          - 0.2617
          - 0.1825
          - 0.1308
