_target_: ophthalmology.modules.disease_grading.DiseaseGrading

#optimizer
learning_rate: 3e-3
weight_decay: 1e-4
batch_size: ${datamodule.batch_size}
epochs: ${trainer.max_epochs}
num_train_samples: 276

#debugging/logging
print_model_info_for_input:
  - 1024
  - 3
  - ${datamodule.image_size}
  - ${datamodule.image_size}
