_target_: ophthalmology.modules.simclr.SimCLR

#model
num_features: 2048
num_hidden_projection_features: 64
num_projection_features: 32

#loss
temperature: 0.1

#optimizer
learning_rate: 3e-3
weight_decay: 1e-4
epochs: ${trainer.max_epochs}
num_train_samples: 88693
batch_size: ${datamodule.batch_size}

#debugging/logging
print_model_info_for_input:
  - 8
  - 3
  - ${image_size}
  - ${image_size}
