_target_: opthalmology.modules.simclr.SimCLR

#model
num_features: ${model.num_features}
num_hidden_projection_features: 64
num_projection_features: 32

#loss
temperature: 0.1

#optimizer
learning_rate: 3e-3
weight_decay: 1e-4
epochs: ${trainer.max_epochs}
num_train_samples: ???
batch_size: ${datamodule.batch_size}

#debugging/logging
print_model_info_for_input:
  - 1024
  - 3
  - ${datamodule.image_size}
  - ${datamodule.image_size}
